name: "Build NixOS ISOs"
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 1 */3 *'
jobs:
  buildiso:
    if: (startsWith(github.event.head_commit.message, 'buildiso:') || (github.event_name == 'schedule'))
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: |
        echo "::set-output name=tag-date::$(date +'release/%F/%H.%M')"
        echo "::set-output name=date::$(date +'%F %H:%M')"
        
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Bind mount /nix
      run: |
        mkdir -p $GITHUB_WORKSPACE/nix
        sudo mkdir -p /nix
        sudo mount --bind $GITHUB_WORKSPACE/nix /nix
        
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'nixos-config'

    - name: Install nix
      uses: cachix/install-nix-action@v16

    - name: Build ISO
      run: |
        nix build ./nixos-config#nixosConfigurations.live-iso.config.system.build.isoImage

    - name: ISO metadata
      id: iso_metadata
      run: |
        echo "::set-output name=mbund-nixos-live-iso-hash::$(sha512sum result/iso/mbund-nixos-live.iso | cut -d " " -f 1)"

    - name: Split ISO
      run: |
        split -b $((2147483647 - 1024)) result/iso/mbund-nixos-live.iso mbund-nixos-live-part-

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.date.outputs.tag-date }}"
        prerelease: false
        title: "ISOs"
        files: |
          mbund-nixos-live-part-*

    - name: Clean up releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

