name: "Build NixOS ISOs"
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 1 */3 *'
jobs:
  buildiso:
    if: (startsWith(github.event.head_commit.message, 'buildiso:') || (github.event_name == 'schedule'))
    runs-on: ubuntu-latest
    steps:
    - name: Debugging 1
      run: |
        echo pwd: $(pwd)
        echo GITHUB_WORKSPACE: $GITHUB_WORKSPACE
        
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        
    - name: Get current date
      id: date
      run: |
        echo "::set-output name=date::$(date +'%F %H:%M')"
    
    - name: Debugging 2
      run: |
        echo pwd: $(pwd)
        echo GITHUB_WORKSPACE: $GITHUB_WORKSPACE
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install nix
      uses: cachix/install-nix-action@v16

    - name: Build ISO
      id: iso
      run: |
        nix build .#nixosConfigurations.live-iso.config.system.build.isoImage
        cp result/iso/mbund-nixos-live.iso mbund-nixos-live.iso
        echo "::set-output name=mbund-nixos-live-iso-hash::$(sha512sum mbund-nixos-live.iso | cut -d " " -f 1)"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          mbund-nixos-live.iso
        body: |
          SHA-512 checksum of the Live ISO: ${{ steps.iso.outputs.mbund-nixos-live-iso-hash }}.
        tag_name: autobuild
        name: ${{ steps.date.outputs.date }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

