name: "Build NixOS ISOs"
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 1 */3 *'
jobs:
  buildiso:
    if: (startsWith(github.event.head_commit.message, 'buildiso:') || (github.event_name == 'schedule'))
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: |
        echo "::set-output name=tag-date::$(date +'release/%F/%H.%M')"
        echo "::set-output name=iso-date::$(date +'%F-%H-%M')"

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Bind mount /nix
      run: |
        mkdir -p $GITHUB_WORKSPACE/nix
        sudo mkdir -p /nix
        sudo mount --bind $GITHUB_WORKSPACE/nix /nix

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'nixos-config'

    - name: Install nix
      uses: cachix/install-nix-action@v16

    - name: Build nixos-installer.iso
      id: build-installer-iso
      run: |
        nix build ./nixos-config#nixosConfigurations.installer-iso.config.system.build.isoImage
        cp result/iso/nixos-installer.iso nixos-installer-${{ steps.date.outputs.iso-date }}.iso
        echo "::set-output name=nixos-installer-iso-hash::$(sha512sum result/iso/nixos-installer.iso | cut -d " " -f 1)"

    - name: Release nixos-installer.iso
      uses: softprops/action-gh-release@v1
      with:
        name: Installer
        tag_name: ${{ steps.date.outputs.tag-date }}
        body: |
          Custom NixOS installer iso, including the following goodies:
          - The latest Linux kernel, for maximum compatibility
          - Nix Flakes enabled out of the box
          - `zsh` with syntax highlighting, completion, etc. (still POSIX just nicer)
          - `vim` with sane defaults and syntax highlighting for the Nix Expression Language

          SHA-512 checksum: `${{ steps.build-installer-iso.outputs.nixos-installer-iso-hash }}`

        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          nixos-installer-*.iso
