name: "Build NixOS ISOs"
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 1 */3 *'
jobs:
  buildiso:
    if: (startsWith(github.event.head_commit.message, 'buildiso:') || (github.event_name == 'schedule'))
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: |
        echo "::set-output name=date::$(date +'%F %H:%M')"

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Bind mount /nix
      run: |
        mkdir -p $GITHUB_WORKSPACE/nix
        sudo mkdir -p /nix
        sudo mount --bind $GITHUB_WORKSPACE/nix /nix

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'nixos-config'

    - name: Install nix
      uses: cachix/install-nix-action@v16

    - name: Build nixos-installer.iso
      id: build-installer-iso
      run: |
        nix build ./nixos-config#nixosConfigurations.installer-iso.config.system.build.isoImage
        cp result/iso/nixos-installer.iso nixos-installer.iso
        echo "::set-output name=nixos-installer-iso-hash::$(sha512sum nixos-installer.iso | cut -d " " -f 1)"

    - name: Release nixos-installer.iso
      uses: softprops/action-gh-release@v1
      with:
        name: Installer
        tag_name: installer-iso-latest
        body: |
          Custom NixOS installer iso, including the latest kernel and other updates, along with flakes enabled out of the box.

          SHA-512 checksum of `nixos-installer.iso`: `${{ steps.build-installer-iso.outputs.nixos-installer-iso-hash }}`

        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          nixos-installer.iso


    - name: Build nixos-installer-riced.iso
      id: build-installer-riced-iso
      run: |
        nix build ./nixos-config#nixosConfigurations.installer-iso-riced.config.system.build.isoImage
        cp result/iso/nixos-installer-riced.iso nixos-installer-riced.iso
        echo "::set-output name=nixos-installer-iso-riced-hash::$(sha512sum nixos-installer-riced.iso | cut -d " " -f 1)"

    - name: Release nixos-installer-riced.iso
      uses: softprops/action-gh-release@v1
      with:
        name: Installer Riced
        tag_name: installer-riced-iso-latest
        body: |
          Custom NixOS installer iso, including the latest kernel and other updates, along with flakes enabled out of the box. This one (riced) includes my own quality of life additions (such as zsh & friends instead of bash).

          SHA-512 checksum of `nixos-installer-riced.iso`: `${{ steps.build-installer-riced-iso.outputs.nixos-installer-riced-iso-hash }}`

        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          nixos-installer-riced.iso

