name: "Build NixOS ISOs"
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 1 */3 *'
jobs:
  buildiso:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H')"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install nix
      uses: cachix/install-nix-action@v16

    - name: Build ISO
      id: iso
      run: |
        nix build .#live-iso
        cp result/iso/mbund-nixos-live.iso mbund-nixos-live.iso
        echo "::set-output name=mbund-nixos-live-iso-hash::$(sha512sum mbund-nixos-live.iso | cut -d " " -f 1)"

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.date.outputs.date }}
        release_name: ${{ steps.date.outputs.date }}
        body: |
          SHA-512 checksum of the Live ISO: ${{ steps.iso.outputs.mbund-nixos-live-iso-hash }}.
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: mbund-nixos-live.iso
        asset_name: mbund-nixos-live-${{ steps.date.outputs.date }}.iso
        asset_content_type: application/x-iso9660-image

    - name: Clean up releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

