name: "Nix Tests"
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install nix
      uses: cachix/install-nix-action@v16

    - name: Flake metadata
      run: nix flake metadata

    - name: Flake outputs
      run: nix flake show

    - name: Check
      run: nix flake check

