name: "Build NixOS ISOs"
on:
  pull_request:
  push:
jobs:
  buildiso:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: |
        echo "::set-output name=tag-date::$(date +'release/%F/%H.%M')"
        echo "::set-output name=date::$(date +'%F %H:%M')"

    - name: Produce temp file
      id: iso_metadata
      run: |
        echo "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890" > mbund-nixos-live.iso
        echo "::set-output name=mbund-nixos-live-iso-hash::$(sha512sum mbund-nixos-live.iso | cut -d " " -f 1)"

    - name: Split ISO
      run: |
        split -b 4 result/iso/mbund-nixos-live.iso mbund-nixos-live-

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          mbund-nixos-live-*
        body: |
          The iso is distributed in 2gb binary chunks, and must be each separately downloaded and reconstructed locally.
          
          powershell:
          ```
          copy /b mbund-nixos-live-aa mbund-nixos-live-ab mbund-nixos-live-ac mbund-nixos-live.iso
          ```
          *nix:
          ```
          cat mbund-nixos-live-a{a..c} > mbund-nixos-live.iso
          ```
          SHA-512 checksum of the Live ISO: ${{ steps.iso_metadata.outputs.mbund-nixos-live-iso-hash }}.
          
        tag_name: ${{ steps.date.outputs.tag-date }}
        name: ${{ steps.date.outputs.date }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

